apiVersion: v1
kind: Template
metadata:
  name: hybrid-usecase-oidc
objects:
- kind: "BuildConfig"
  apiVersion: "v1"
  metadata:
    name: "hybrid-usecase-oidc-${TARGET_INSTANCE}"
    namespace: ${NAMESPACE}
  spec:
    source:
      git:
        uri: ${GIT_REPO}
    strategy:
      type: "JenkinsPipeline"
      jenkinsPipelineStrategy:
        jenkinsfilePath: hybrid-usecase-oidc/Jenkinsfile
        env:
          - name: SECRET_NAME
            value: ${SECRET_NAME}
          - name: NAMESPACE
            value: ${NAMESPACE}
          - name: TARGET_INSTANCE
            value: ${TARGET_INSTANCE}
          - name: PUBLIC_STAGING_WILDCARD_DOMAIN
            value: ${PUBLIC_STAGING_WILDCARD_DOMAIN}
          - name: PUBLIC_PRODUCTION_WILDCARD_DOMAIN
            value: ${PUBLIC_PRODUCTION_WILDCARD_DOMAIN}
          - name: DEVELOPER_ACCOUNT_ID
            value: ${DEVELOPER_ACCOUNT_ID}
          - name: PRIVATE_BASE_URL
            value: ${PRIVATE_BASE_URL}
          - name: OIDC_ISSUER_ENDPOINT
            value: ${OIDC_ISSUER_ENDPOINT}
          - name: DISABLE_TLS_VALIDATION
            value: ${DISABLE_TLS_VALIDATION}
parameters:
- name: SECRET_NAME
  value: 3scale-toolbox
- name: NAMESPACE
  value: api-lifecycle
- name: TARGET_INSTANCE
  required: true
- name: GIT_REPO
  value: https://github.com/rh-integration/3scale-toolbox-jenkins-samples.git
- name: PUBLIC_STAGING_WILDCARD_DOMAIN
  required: true
- name: PUBLIC_PRODUCTION_WILDCARD_DOMAIN
  required: true
- name: DEVELOPER_ACCOUNT_ID
  required: true
- name: PRIVATE_BASE_URL
  required: true
- name: OIDC_ISSUER_ENDPOINT
  required: true
- name: DISABLE_TLS_VALIDATION
  value: "no"
